### ISSUE TITLE
Workspaces have to be pulled over http, cannot pull a workspace from a local file

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk#24]
```
<?xml version="1.0" ?>
<channels>
        <components>
                <type>source</type>
                <path>/home/chris/pdk/channels/debian/jessie/rpi/</path>
        </components>
</channels>
```

error:

```
chris@apollo:~/pdk/projects/peidi$ pdk pull components
Counting objects: 23, done.
Compressing objects: 100% (21/21), done.
Total 23 (delta 16), reused 0 (delta 0)
Counting objects: 23, done.
Compressing objects: 100% (21/21), done.
Traceback (most recent call last):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 12: ordinal not in range(128)
pdk ERROR: Unknown error
fatal: sha1 file '<stdout>' write error: Broken pipe
fatal: early EOF
pdk ERROR: Operation cannot be performed: command "('/bin/sh', ['/bin/sh', '-c', '{ git unpack-objects ; } '])" failed: 32768
```

When using this `channels.xml` file, I cannot doa  `pdk pull components` command. This works fine if the file is being served over HTTP.

A workaround, for now, is to setup an HTTP server for this purpose.

**Comment by danielhjames** [comment]
I have seen the 'UnicodeDecodeError: 'ascii' codec can't decode' error before with another Python 2.x program, it happens when a file contains any character with an accent. For example a European name of a package maintainer in a Debian release file might trigger this. Presumably when served over http, the file is handled properly as UTF-8.
