### ISSUE TITLE
Update packaging to allow for new Imggen commands & package version 1.0.0 Alpha

### ISSUE THREAD

**Issue by obbardc** [64studio/pdk#31]
I am (nearly) sure the Debian packages needed are `dosfstools debootstrap dmsetup kpartx mount qemu-user-static`

Should we make these depends of a seperate package: pdk-imggen OR just pollute the main package with these additional depends?  But the likeliness of a user installing PDK without the Imggen command is quite unlikely.

Also, we need to generate some new packages and host them for version 1.0 unstable testing. Dan, can you look a bit into http://packagecloud.io again?

I've not bothered to update the `debian/changelog` in a while.

A neat way would be an auto-deb-generator which updates the repository on every Git commit ;-). This would also be very useful for our other projects.....

**Comment by danielhjames** [comment]
Hi Chris, I don't think we need a separate pdk-imggen page, let's roll these changes into the main pdk package.

We previously set up https://packagecloud.io/64studio/pdk/ but although it hosts some Jessie packages I haven't really used it yet.

You can see an example of an auto package building script at https://github.com/Airtime/airtime-packaging/blob/master/gen-deb-package.sh - I guess you could trigger something this with a GitHub webhook, but you would still need a third-party build machine since I don't think Packagecloud hosts anything like pbuilder or git-buildpackage.

**Comment by obbardc** [comment]
I'm almost ready to release 1.0.0 alpha 1, after updating the packaging files etc.  I will update the `debian/changelog` file to be version `1.0.0~alpha1` if you think this is OK.

What shall we set the version of our patched Smart to be? Currently it is `1.4-2` but we can call it `1.4-2~pdk1` or something? And then depend on this **exact** version in our `debian/control`?

**Comment by danielhjames** [comment]
Sounds good!

**Comment by obbardc** [comment]
Version 1.0.0~alpha1 released! Closed.
